name: Test notebooks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run_all_notebooks:
    name: Run all notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          channel-priority: true
          activate-environment: workshop-itn-potsdam-2023-01
          environment-file: environment.yml
          miniforge-version: latest
          miniforge-variant: Mambaforge
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Install dev dependencies
        shell: bash -l {0}
        run: |
          mamba install papermill nbconvert
      - name: Execute all notebooks
        shell: bash -l {0}
        run: python execute_all_notebooks.py
